"""
Skills Self-Evolution Manager
负责跟踪 Skills 进化历史，判断触发条件，执行 Skills 更新。
触发条件（满足任一即触发）：
  1. 同一失误类型出现 ≥2 次
  2. 积累入库记录 ≥50 条
  3. P0 拦截率 > 5%
"""
import json
import uuid
from datetime import datetime
from pathlib import Path
from typing import Optional

from app.config import DATA_DIR, SKILLS_DIR

SKILLS_INDEX = SKILLS_DIR / "skills_index.json"
EVOLUTION_LOG = SKILLS_DIR / "evolution_log.json"


def _load_json(path: Path) -> dict:
    if not path.exists():
        return {}
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def _save_json(path: Path, data: dict) -> None:
    SKILLS_DIR.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)


# ─── Skills Index ──────────────────────────────────────────────────────────────

def get_skills_index() -> dict:
    return _load_json(SKILLS_INDEX)


def upsert_skill(skill_id: str, content: str, version: str, trigger: str) -> dict:
    """写入或更新一个 Skill 文件，并更新索引。"""
    skill_file = SKILLS_DIR / f"{skill_id}.md"
    skill_file.write_text(content, encoding="utf-8")

    index = get_skills_index()
    index[skill_id] = {
        "version": version,
        "updated_at": datetime.utcnow().isoformat(),
        "trigger": trigger,
        "file": str(skill_file),
        "changelog": index.get(skill_id, {}).get("changelog", []),
    }
    index[skill_id]["changelog"].append({
        "version": version,
        "updated_at": datetime.utcnow().isoformat(),
        "trigger": trigger,
    })
    _save_json(SKILLS_INDEX, index)
    return index[skill_id]


# ─── Evolution Log ─────────────────────────────────────────────────────────────

def get_evolution_log() -> list:
    return _load_json(EVOLUTION_LOG).get("entries", [])


def log_evolution(
    iteration: int,
    trigger_reason: str,
    patterns_found: list[dict],
    skills_updated: list[str],
    run_id: str,
) -> None:
    """记录一次进化事件。"""
    log = _load_json(EVOLUTION_LOG)
    entry = {
        "id": str(uuid.uuid4()),
        "run_id": run_id,
        "iteration": iteration,
        "trigger_reason": trigger_reason,
        "patterns_found": patterns_found,
        "skills_updated": skills_updated,
        "logged_at": datetime.utcnow().isoformat(),
    }
    log.setdefault("entries", [])
    log["entries"].insert(0, entry)
    # 只保留最近20条
    log["entries"] = log["entries"][:20]
    _save_json(EVOLUTION_LOG, log)


def get_next_iteration() -> int:
    log = _load_json(EVOLUTION_LOG)
    entries = log.get("entries", [])
    return max([e["iteration"] for e in entries], default=0) + 1


# ─── Trigger Decision ─────────────────────────────────────────────────────────

def should_evolve(
    recent_mistakes: list[dict],
    total入库: int,
    p0_rate: float,
) -> tuple[bool, str]:
    """
    判断是否应触发 Skills 自进化。
    返回 (should_evolve, reason)
    """
    # 条件1：同类失误 ≥2 次
    mistake_count: dict[str, int] = {}
    for m in recent_mistakes:
        key = m.get("type", "unknown")
        mistake_count[key] = mistake_count.get(key, 0) + 1
    for mistake_type, count in mistake_count.items():
        if count >= 2:
            return True, f"同类失误「{mistake_type}」出现 {count} 次"

    # 条件2：积累入库记录 ≥50
    if total入库 >= 50:
        return True, f"积累入库记录 {total入库} 条"

    # 条件3：P0 拦截率 > 5%
    if p0_rate > 0.05:
        return True, f"P0 拦截率 {p0_rate:.1%} > 5%"

    return False, ""


# ─── 模拟 Skills 内容更新（实际可替换为 Agent 生成）─────────────────────────────

def generate_skill_update(skill_id: str, patterns: list[dict]) -> str:
    """
    基于失误 pattern 生成/更新 Skill 内容。
    这里用模板生成，实际可接 Claude 等 LLM 生成真实内容。
    """
    timestamp = datetime.utcnow().strftime("%Y-%m-%d")
    patterns_md = "\n".join(
        f"- **{p.get('type','未知类型')}**：{p.get('description','')} （发现次数：{p.get('count',1)}）"
        for p in patterns
    )
    content = f"""# {skill_id} Skill

> Auto-generated by SOTA Radar Self-Evolution · {timestamp}
> 此文件由 SelfReview Agent 自动更新，请勿手动修改。

## 触发原因

本次更新由 Skills Self-Evolution 机制自动触发。

## 发现的问题模式

{patterns_md}

## 更新内容

### 规则强化

基于上述问题模式，已更新以下检查规则：

1. **Benchmark 数据字段**：入库模型必须包含 ≥1 个 Benchmark 数据，空值拒绝入库
2. **许可证校验**：所有模型入库前必须确认许可证类型，禁止上传 license=unknown 的模型
3. **信息源优先级**：所有描述必须标注信息来源（T0/T1/T2），无来源标注的描述不得入库
4. **日期精确性**：发布日期必须精确到日，模糊日期（如"2024年"）按 P1 处理

### 自审检查清单

- [ ] 每条入库记录包含 Benchmark 数据
- [ ] 许可证字段已确认，非 unknown
- [ ] 所有信息源已标注优先级
- [ ] 日期精确到日

## 版本历史

- **{timestamp}**：由 SelfReview Agent 基于 {len(patterns)} 个失误 pattern 自动更新

"""
    return content


# ─── 执行一次完整的自进化 ──────────────────────────────────────────────────────

def run_self_evolution(run_id: str, recent_mistakes: list[dict], total入库: int, p0_rate: float) -> dict:
    """
    执行 Skills 自进化主流程。
    """
    should, reason = should_evolve(recent_mistakes, total入库, p0_rate)
    iteration = get_next_iteration()

    result = {
        "run_id": run_id,
        "iteration": iteration,
        "triggered": should,
        "trigger_reason": reason,
        "skills_updated": [],
        "patterns_found": [],
    }

    if not should:
        result["trigger_reason"] = "未达到触发阈值（同类失误<2次，入库<50条，P0拦截率≤5%）"
        log_evolution(
            iteration=iteration,
            trigger_reason=reason or "未触发",
            patterns_found=[],
            skills_updated=[],
            run_id=run_id,
        )
        return result

    # 识别失误类型
    patterns: dict[str, dict] = {}
    for m in recent_mistakes:
        key = m.get("type", "unknown")
        if key not in patterns:
            patterns[key] = {"type": key, "description": m.get("description", ""), "count": 0}
        patterns[key]["count"] += 1

    pattern_list = list(patterns.values())

    # 找出需要更新的 Skills
    skill_ids_to_update = set()
    for p in pattern_list:
        if p["type"] in ("benchmark缺失", "benchmark数据不完整"):
            skill_ids_to_update.add("researcher")
        elif p["type"] in ("许可证错误", "license未知"):
            skill_ids_to_update.add("reviewer")
        elif p["type"] in ("日期模糊", "来源缺失"):
            skill_ids_to_update.add("researcher")
            skill_ids_to_update.add("reviewer")
        else:
            skill_ids_to_update.add("self-review")

    # 更新每个 Skill
    new_version = f"v{iteration}.0"
    for skill_id in skill_ids_to_update:
        content = generate_skill_update(skill_id, pattern_list)
        version_tag = f"{new_version}-{skill_id}"
        upsert_skill(skill_id, content, version_tag, reason)

    result["patterns_found"] = pattern_list
    result["skills_updated"] = list(skill_ids_to_update)

    log_evolution(
        iteration=iteration,
        trigger_reason=reason,
        patterns_found=pattern_list,
        skills_updated=list(skill_ids_to_update),
        run_id=run_id,
    )

    return result
