name: Version Tag

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (e.g. v4.0)'
        required: true

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create tag
        run: |
          git config user.name "SOTA Radar CI"
          git config user.email "ci@sota-radar.ai"
          git tag ${{ github.event.inputs.version }}
          git push origin ${{ github.event.inputs.version }}
