/**
 * Static fallback data — used when backend API is unavailable.
 * Mirrors the ModelSummary interface from api.ts.
 */
import type { ModelSummary } from './api'

export const staticModels: ModelSummary[] = [
  {
    id: 'glm-5',
    name: 'GLM-5',
    category: 'Text',
    publisher: '智谱AI',
    params: '130B',
    license_tag: 'Apache-2.0',
    is_sota: true,
    updated_at: '2026-04-05T10:00:00Z',
  },
  {
    id: 'qwen3-235b',
    name: 'Qwen3-235B-A22B',
    category: 'Text',
    publisher: '阿里云',
    params: '235B',
    license_tag: 'Apache-2.0',
    is_sota: true,
    updated_at: '2026-04-05T09:00:00Z',
  },
  {
    id: 'deepseek-v3',
    name: 'DeepSeek-V3',
    category: 'Text',
    publisher: 'DeepSeek',
    params: '236B',
    license_tag: 'MIT',
    is_sota: true,
    updated_at: '2026-04-04T14:00:00Z',
  },
  {
    id: 'step-3-5-flash',
    name: 'Step-3.5-Flash',
    category: 'Embedding',
    publisher: '阶跃星辰',
    params: '7B',
    license_tag: 'Apache-2.0',
    is_sota: false,
    updated_at: '2026-04-05T08:00:00Z',
  },
  {
    id: 'cogvideox-5b',
    name: 'CogVideoX-5B',
    category: 'Video',
    publisher: '智谱AI',
    params: '5B',
    license_tag: 'Apache-2.0',
    is_sota: false,
    updated_at: '2026-04-04T12:00:00Z',
  },
  {
    id: 'hunievideo',
    name: 'HunieVideo',
    category: 'Video',
    publisher: '字节跳动',
    params: '17B',
    license_tag: 'MIT',
    is_sota: false,
    updated_at: '2026-04-04T10:00:00Z',
  },
  {
    id: 'qwq-32b',
    name: 'QwQ-32B',
    category: 'Text',
    publisher: '阿里云',
    params: '32B',
    license_tag: 'Apache-2.0',
    is_sota: false,
    updated_at: '2026-04-03T16:00:00Z',
  },
  {
    id: 'qwen2-72b',
    name: 'Qwen2-72B-Instruct',
    category: 'Text',
    publisher: '阿里云',
    params: '72B',
    license_tag: 'Apache-2.0',
    is_sota: false,
    updated_at: '2026-04-03T08:00:00Z',
  },
  {
    id: 'glm-4',
    name: 'GLM-4',
    category: 'Text',
    publisher: '智谱AI',
    params: '9B',
    license_tag: 'Apache-2.0',
    is_sota: false,
    updated_at: '2026-04-02T14:00:00Z',
  },
  {
    id: 'mistral-small',
    name: 'Mistral Small 4',
    category: 'Text',
    publisher: 'Mistral AI',
    params: '22B',
    license_tag: 'Apache-2.0',
    is_sota: false,
    updated_at: '2026-04-01T18:00:00Z',
  },
  {
    id: 'minimax-text01',
    name: 'MiniMax-Text-01',
    category: 'Text',
    publisher: 'MiniMax',
    params: '456B',
    license_tag: 'Apache-2.0',
    is_sota: true,
    updated_at: '2026-04-05T11:00:00Z',
  },
  {
    id: 'bailing-world',
    name: 'Bailing-World',
    category: 'Multimodal',
    publisher: '字节跳动',
    params: '35B',
    license_tag: 'Custom',
    is_sota: false,
    updated_at: '2026-04-04T20:00:00Z',
  },
]

// Enrich static models with insight for search
export const staticModelInsights: Record<string, string> = {
  'glm-5': 'SWE-bench 77.8%，MMLU 92.4%，推理能力强，支持128K上下文',
  'qwen3-235b': 'MMLU 91.2%，支持工具调用和代码执行，开源最强',
  'deepseek-v3': 'MMLU 90.8%，MoE架构，训练成本低',
  'step-3-5-flash': 'Embedding模型，支持多语言，推理速度快',
  'cogvideox-5b': '文生视频模型，支持16秒视频生成，影视级效果',
  'hunievideo': '字节视频生成模型，支持高清视频合成',
  'qwq-32b': '数学推理能力强，AIME 72.3%',
  'qwen2-72b': '通用能力强，代码生成优秀',
  'glm-4': 'MMLU 89.7%，国产性价比之选',
  'mistral-small': 'Mistral小杯，SWE-bench 73.1%',
  'minimax-text01': '456B超大规模，MMLU 93.1%，国产最强',
  'bailing-world': '多模态统一模型，支持图文视频混合推理',
}
