// dataA — Truth cases for the Truth Filter section (embedded truthCases here)
export const truthCases = [
  {
    id: 'tc1',
    time: '13:18',
    model: 'Mistral Small 4',
    source: 'Mistral 官方博客',
    sourceUrl: undefined as string | undefined,
    claim: '"全球最强开源模型"',
    verdict: '夸大其词',
    ourVerdict: 'QC 实测 SWE-bench 73.1%，落后 GLM-5 的 77.8%，→ 降级为"特色模型待补"，去除 SOTA 标签',
    evidence: [
      { label: '宣传 SWE-bench', val: '~78%', source: '官方博客', sourceUrl: undefined },
      { label: '实测 SWE-bench', val: '73.1%', source: 'SWE-bench官方', sourceUrl: undefined },
      { label: 'vs GLM-5', val: '77.8%', source: 'GLM官方', sourceUrl: undefined },
    ],
    lesson: '教训：许可证正确 ≠ SOTA。Benchmark缺失 = 不能声称SOTA。',
    exactQuote: 'We are proud to announce Mistral Small 4, the world\'s most powerful open-source model.',
  },
  {
    id: 'tc2',
    time: '13:12',
    model: 'Qwen3.6-Plus',
    source: '阿里云博客',
    sourceUrl: undefined as string | undefined,
    claim: '"多模态能力全面升级"',
    verdict: '待核实',
    ourVerdict: '发现 BuildFastWithAI 称 text-only，阿里博客提及视觉感知，→ 有条件入库，标注 ⚠️ 模态待核实',
    evidence: [
      { label: 'BuildFastWithAI', val: 'text-only', source: 'BuildFastWithAI', sourceUrl: undefined },
      { label: '阿里博客', val: '视觉感知', source: '阿里云官方博客', sourceUrl: undefined },
      { label: '官方确认', val: '暂无', source: '—', sourceUrl: undefined },
    ],
    lesson: '分类争议影响使用场景判断。入库前必须等官方确认。',
    exactQuote: 'Qwen3.6-Plus brings comprehensive multimodal capability upgrades.',
  },
  {
    id: 'tc3',
    time: '13:05',
    model: 'Step-3.5-Flash',
    source: 'HuggingFace',
    sourceUrl: undefined as string | undefined,
    claim: '"国产最强 Embedding"',
    verdict: '证据不足',
    ourVerdict: 'HF 页面无 Benchmark 数据，许可证显示 unknown，→ P0-3 门禁触发：license=unknown 不得入库，已拦截',
    evidence: [
      { label: 'Benchmark数据', val: '无', source: 'HuggingFace页面', sourceUrl: undefined },
      { label: '许可证', val: 'unknown', source: 'HuggingFace页面', sourceUrl: undefined },
      { label: 'P0门禁', val: '拒绝入库', source: 'QC门禁', sourceUrl: undefined },
    ],
    lesson: 'HF 页面上有 ≠ 可商用。未核实前不得声明。',
    exactQuote: 'Step-3.5-Flash: the best Chinese Embedding model.',
  },
]
